// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: assets.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       map[string]string      `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsRequest) Reset() {
	*x = GetAssetsRequest{}
	mi := &file_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsRequest) ProtoMessage() {}

func (x *GetAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsRequest) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{0}
}

func (x *GetAssetsRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type CrosspromoFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdType        string                 `protobuf:"bytes,1,opt,name=AdType,proto3" json:"AdType,omitempty"`
	AdFormat      string                 `protobuf:"bytes,2,opt,name=AdFormat,proto3" json:"AdFormat,omitempty"`
	FileSize      int32                  `protobuf:"varint,3,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrosspromoFile) Reset() {
	*x = CrosspromoFile{}
	mi := &file_assets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrosspromoFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrosspromoFile) ProtoMessage() {}

func (x *CrosspromoFile) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrosspromoFile.ProtoReflect.Descriptor instead.
func (*CrosspromoFile) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{1}
}

func (x *CrosspromoFile) GetAdType() string {
	if x != nil {
		return x.AdType
	}
	return ""
}

func (x *CrosspromoFile) GetAdFormat() string {
	if x != nil {
		return x.AdFormat
	}
	return ""
}

func (x *CrosspromoFile) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CrosspromoFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AdTypeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Data          []*CrosspromoFile      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdTypeData) Reset() {
	*x = AdTypeData{}
	mi := &file_assets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdTypeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdTypeData) ProtoMessage() {}

func (x *AdTypeData) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdTypeData.ProtoReflect.Descriptor instead.
func (*AdTypeData) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{2}
}

func (x *AdTypeData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdTypeData) GetData() []*CrosspromoFile {
	if x != nil {
		return x.Data
	}
	return nil
}

type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AdType        map[string]*AdTypeData `protobuf:"bytes,2,rep,name=AdType,proto3" json:"AdType,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_assets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{3}
}

func (x *Platform) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Platform) GetAdType() map[string]*AdTypeData {
	if x != nil {
		return x.AdType
	}
	return nil
}

type Localization struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LocalizationCode string                 `protobuf:"bytes,1,opt,name=localizationCode,proto3" json:"localizationCode,omitempty"`
	Platforms        []*Platform            `protobuf:"bytes,2,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Localization) Reset() {
	*x = Localization{}
	mi := &file_assets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Localization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Localization) ProtoMessage() {}

func (x *Localization) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Localization.ProtoReflect.Descriptor instead.
func (*Localization) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{4}
}

func (x *Localization) GetLocalizationCode() string {
	if x != nil {
		return x.LocalizationCode
	}
	return ""
}

func (x *Localization) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

// Изменяем ответ на просто массив Localization
type GetAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Localizations []*Localization        `protobuf:"bytes,1,rep,name=localizations,proto3" json:"localizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsResponse) Reset() {
	*x = GetAssetsResponse{}
	mi := &file_assets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsResponse) ProtoMessage() {}

func (x *GetAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsResponse) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssetsResponse) GetLocalizations() []*Localization {
	if x != nil {
		return x.Localizations
	}
	return nil
}

var File_assets_proto protoreflect.FileDescriptor

const file_assets_proto_rawDesc = "" +
	"\n" +
	"\fassets.proto\x12\x06assets\"\x8f\x01\n" +
	"\x10GetAssetsRequest\x12?\n" +
	"\afilters\x18\x01 \x03(\v2%.assets.GetAssetsRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x0eCrosspromoFile\x12\x16\n" +
	"\x06AdType\x18\x01 \x01(\tR\x06AdType\x12\x1a\n" +
	"\bAdFormat\x18\x02 \x01(\tR\bAdFormat\x12\x1a\n" +
	"\bFileSize\x18\x03 \x01(\x05R\bFileSize\x12\x10\n" +
	"\x03Url\x18\x04 \x01(\tR\x03Url\"N\n" +
	"\n" +
	"AdTypeData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.assets.CrosspromoFileR\x04data\"\xa3\x01\n" +
	"\bPlatform\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06AdType\x18\x02 \x03(\v2\x1c.assets.Platform.AdTypeEntryR\x06AdType\x1aM\n" +
	"\vAdTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.assets.AdTypeDataR\x05value:\x028\x01\"j\n" +
	"\fLocalization\x12*\n" +
	"\x10localizationCode\x18\x01 \x01(\tR\x10localizationCode\x12.\n" +
	"\tplatforms\x18\x02 \x03(\v2\x10.assets.PlatformR\tplatforms\"O\n" +
	"\x11GetAssetsResponse\x12:\n" +
	"\rlocalizations\x18\x01 \x03(\v2\x14.assets.LocalizationR\rlocalizations2S\n" +
	"\rAssetsService\x12B\n" +
	"\tGetAssets\x12\x18.assets.GetAssetsRequest\x1a\x19.assets.GetAssetsResponse\"\x00B@Z>github.com/polyakovWeb/crosspromo_backend_go/cmd/server/assetsb\x06proto3"

var (
	file_assets_proto_rawDescOnce sync.Once
	file_assets_proto_rawDescData []byte
)

func file_assets_proto_rawDescGZIP() []byte {
	file_assets_proto_rawDescOnce.Do(func() {
		file_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assets_proto_rawDesc), len(file_assets_proto_rawDesc)))
	})
	return file_assets_proto_rawDescData
}

var file_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_assets_proto_goTypes = []any{
	(*GetAssetsRequest)(nil),  // 0: assets.GetAssetsRequest
	(*CrosspromoFile)(nil),    // 1: assets.CrosspromoFile
	(*AdTypeData)(nil),        // 2: assets.AdTypeData
	(*Platform)(nil),          // 3: assets.Platform
	(*Localization)(nil),      // 4: assets.Localization
	(*GetAssetsResponse)(nil), // 5: assets.GetAssetsResponse
	nil,                       // 6: assets.GetAssetsRequest.FiltersEntry
	nil,                       // 7: assets.Platform.AdTypeEntry
}
var file_assets_proto_depIdxs = []int32{
	6, // 0: assets.GetAssetsRequest.filters:type_name -> assets.GetAssetsRequest.FiltersEntry
	1, // 1: assets.AdTypeData.data:type_name -> assets.CrosspromoFile
	7, // 2: assets.Platform.AdType:type_name -> assets.Platform.AdTypeEntry
	3, // 3: assets.Localization.platforms:type_name -> assets.Platform
	4, // 4: assets.GetAssetsResponse.localizations:type_name -> assets.Localization
	2, // 5: assets.Platform.AdTypeEntry.value:type_name -> assets.AdTypeData
	0, // 6: assets.AssetsService.GetAssets:input_type -> assets.GetAssetsRequest
	5, // 7: assets.AssetsService.GetAssets:output_type -> assets.GetAssetsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_assets_proto_init() }
func file_assets_proto_init() {
	if File_assets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assets_proto_rawDesc), len(file_assets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assets_proto_goTypes,
		DependencyIndexes: file_assets_proto_depIdxs,
		MessageInfos:      file_assets_proto_msgTypes,
	}.Build()
	File_assets_proto = out.File
	file_assets_proto_goTypes = nil
	file_assets_proto_depIdxs = nil
}
